@startuml ドメインモデル

(Githubアカウント)
(リポジトリ)
(ローカルリポジトリ)
(リモートリポジトリ)
:ユーザー:
(グラフ)
(ブランチ)
(コミット)
(ログ)
(ローカルブランチ)
(リモートブランチ)
(変更ファイル)

ユーザー o-- Githubアカウント
ユーザー o-- ローカルリポジトリ
ブランチ o-- ログ
ブランチ --|> ローカルブランチ
ブランチ --|> リモートブランチ
リポジトリ o-- ブランチ
リポジトリ o-- グラフ
リポジトリ --|> ローカルリポジトリ
リポジトリ --|> リモートリポジトリ
Githubアカウント o-- リモートリポジトリ
リモートリポジトリ o-- リモートブランチ
ローカルリポジトリ o-- ローカルブランチ
グラフ o-- ブランチ
ログ o-- コミット
グラフ o-- コミット
コミット o-- 変更ファイル


@enduml