@startuml ユースケースパッケージ

package ユーザーパッケージ {
:ユーザー:
(Git CLIがあるかどうかチェック)
(Githubアカウントにログインする)
(Githubアカウントからログアウトする)
(Githubアカウントを変える)
(Githubにプッシュする)
(コミットする)
(ローカルリポジトリへのパスを登録する)
(Statusが見える)
(Addする)
(Resetする)
(リモートの結果を交えたグラフを見る)
(リモートリポジトリのブランチを取得する)
(ログを見る)
(リモートリポジトリをローカルリポジトリに登録する)
}

@enduml