@startuml ユースケースパッケージ

package ユーザーパッケージ {
:ユーザー:
(Githubアカウントにログインする)
(Githubアカウントからログアウトする)
(Githubアカウントを変える)
(Githubにプッシュする)
(コミットする)
(Statusが見える)
(Addする)
(リモートの結果を交えたグラフを見る)
(リモートリポジトリのブランチを取得する)
(ログを見る)
(リモートリポジトリをローカルリポジトリに登録する)
}

@enduml